### ISSUE TITLE
Votação: ExpressJS vs Hapi

### ISSUE THREAD

**Issue by IgorDePaula** [angularjsbr/nGile#11]
De seu voto.

**Comment by jurasseck** [comment]
express

**Comment by samuelcastro** [comment]
hapi

**Comment by FernandoCagale** [comment]
hapi

**Comment by bertoldi11** [comment]
Express

**Comment by IgorDePaula** [comment]
Express

**Comment by jeangomes** [comment]
Express

**Comment by thebergamo** [comment]
Express -> Simples, Minimalista, Flexivel e fácil de integrar
Hapi -> Robusto, Extensível, uma ótima escolha para não iniciantes, pois existe um entendimento melhor do mesmo.

hehe Doge are coming! @greenboxal

**Comment by IgorDePaula** [comment]
Nao entendi bergamo, vc vota em qual framework?

2015-05-13 14:24 GMT-03:00 Marcos Vinicius Bérgamo <notifications@github.com

**Comment by thebergamo** [comment]
Na verdade não escolhi @IgorDePaula, cai de paraquedas hehe... eu particularmente gosto muito do Hapi e recomendo ele, mas dependendo do projeto o Express atende bem.. mas voto no hapi =D

**Comment by alainm** [comment]
a vida é curta, vai de hapi

**Comment by alanhoff** [comment]
Já usei os dois, não quero mais nem ver o Express na minha frente...

**Comment by abernardobr** [comment]
HAPI +1

**Comment by IgorDePaula** [comment]
Votacao encerrada, resultado hapi.

**Comment by samuelcastro** [comment]
Aeee ;)

**Comment by filipedeschamps** [comment]
Eu sempre procuro falar: **na dúvida, escolha o mais popular**

Se você está na dúvida, significa que o domain e as ferramentas não estão claras ao ponto de definir qualquer coisa com segurança. A estratégia por trás de escolher a ferramenta mais popular neste caso é que você irá descobrir mais rapidamente se ela irá servir ou não (por acabar tendo mais recursos disponíveis, seja tutoriais, pessoas, implementações, etc).
