### ISSUE TITLE
Tipo

### ISSUE THREAD

**Issue by IgorDePaula** [angularjsbr/nGile#2]
Deixe aqui, o tipo do projeto

rede social
traducao da api oficial com exemplos em todos os topicos
gestor de projetos.

**Comment by ericalves** [comment]
Gestor de projetos.

**Comment by FernandoCagale** [comment]
Gestor de projetos.

**Comment by douglaslira** [comment]
Rede Social

**Comment by gufigueiredo** [comment]
Gestor de Projetos

**Comment by jurasseck** [comment]
Gestor de Projetos

**Comment by jeangomes** [comment]
Gestor de Projetos

**Comment by samuelcastro** [comment]
Gestor de Projetos

**Comment by joaoqcx** [comment]
Gestor de projetos

**Comment by jcomello** [comment]
Gestor de projetos

**Comment by renebizelli** [comment]
Rede Social

**Comment by IgorDePaula** [comment]
Votação Encerrada
